elac_mapping:
  elbow: 
    name: "ELAC_node_LAN9253"
    gear_ratio: 100.0
    feed_constant: 6000.0
  rotbase:
    name: "ELAC_node_LAN9253"
    gear_ratio: 100.0
    feed_constant: 6000.0
  shoulder_joint:
    name: "ELAC_node_LAN9253"
    gear_ratio: 100.0
    feed_constant: 6000.0
  wrist_pitch:
    name: "ELAC_node_LAN9253"
    gear_ratio: 100.0
    feed_constant: 6000.0
  wrist_roll:
    name: "ELAC_node_LAN9253"
    gear_ratio: 100.0
    feed_constant: 6000.0