controller_manager:
  ros__parameters:
    update_rate: 100

    vhit_elac_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

vhit_elac_controller:
  ros__parameters:
    joints:
      - elac_node

    command_interfaces:
      - position

    state_interfaces:
      - position