name: vhit-robot-rev1-demo

version: '1.2.0'

summary: Tests MoveIt2 config for vhit robot rev1

description: |
  Tests MoveIt2 configuration for the vhit robot rev1 running on top of ros2-base-humble

base: core22

grade: devel
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]

  - build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  vhit-robot-rev1-demo:
    plugin: dump
    source: ./install
    
  scripts:
    plugin: dump
    source: ./scripts
    organize:
      '*': usr/bin/

apps:
  vhit-robot-rev1-demo:
    command: usr/bin/run-demo.sh
    environment:
      ROS_DISTRO: humble
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    plugs:
      - ros-base
      - moveit-runtime
      - network
      - network-bind
      - datalayer
      - datalayer-shm
      - system-files

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
  moveit-runtime:
    interface: content
    content: moveit-runtime
    target: $SNAP/moveit-runtime