name: vhit-robot-rev1-demo

version: '1.3.10'

summary: Tests MoveIt2 config for vhit robot rev1

description: |
  Tests MoveIt2 configuration for the vhit robot rev1 running on top of ros2-base-humble

base: core22

grade: devel
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]

  - build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  vhit-robot-rev1-demo:
    plugin: dump
    source: ./install
    stage-packages:
      # ctrlx datalayer stuff
      - ctrlx-datalayer
      - libzmq5
    
  scripts:
    plugin: dump
    source: ./scripts
    organize:
      '*': usr/bin/

apps:
  vhit-robot-rev1-demo:
    command: usr/bin/run-demo.sh
    environment:
      ROS_DISTRO: humble
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    plugs:
      - ros-base
      - moveit-runtime
      - network
      - network-bind
      - process-control

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
  moveit-runtime:
    interface: content
    content: moveit-runtime
    target: $SNAP/moveit-runtime
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
  datalayer-shm:
    interface: shared-memory
    content: datalayer-shm
    target: $SNAP_DATA/.datalayer